# Generated by Django 2.1.1 on 2018-09-02 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(verbose_name='正文')),
                ('title', models.CharField(default=' ', max_length=100, verbose_name='标题')),
                ('rhythmic', models.CharField(default=' ', max_length=100, verbose_name='词牌名')),
                ('_type', models.CharField(choices=[('S', '诗'), ('C', '词'), ('J', '经'), ('O', '其他')], default='S', max_length=100, verbose_name='类型')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('refer_count', models.IntegerField(default=0, verbose_name='被引用次数')),
                ('author', models.ForeignKey(default='佚名', on_delete=django.db.models.deletion.SET_DEFAULT, to='ebrose.Author', verbose_name='作者')),
            ],
        ),
    ]
