# Generated by Django 2.1.1 on 2018-09-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebrose', '0002_poetry_dynasty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poetry',
            old_name='paragraph',
            new_name='paragraphs',
        ),
    ]
